feat: turn on integration test in ci test process, except the test_200_mnist_refine_model (#7)
- add env var RMTC_RESOURCES to ci-test-process and README
- ignore `tests/integration/test_200_mnist_refine_model.py` because python-opencv's imwrite() fails when writing EXR files.

------

note:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
cv2.error: OpenCV(4.13.0) /io/opencv/modules/imgcodecs/src/grfmt_exr.cpp:103: error: (-213:The function/feature is not implemented) imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326 in function 'initOpenEXR'
```